### ISSUE TITLE
Where to get pkg-config packages for libhardware etc.

### ISSUE THREAD

**Issue by b100dian** [piggz/irremote#1]
Hi, I'm trying to build irremote on my machine, but the sailfish build engine does not have libhardware and android-hardware.
My device (Xiaomi Mi4) does have them, from the adaptation repo, but I cannot get them on the build engine (I'm adding the repo in ssu, refresh in zypper but the libhybris-libhardware package is not founnd).

What do I need on the build engine vm?
Thanks,

**Comment by piggz** [comment]
I use the scratchbox style sdk, not the virtualbox VM.  Can you try that?  I'll try doing it in the VM too.

**Comment by b100dian** [comment]
Thanks for the quick answer!
Indeed, reading the sb2 instructions I figured out the VM also had sdk-assistant et co.
So I entered the sb2 in arm mode and added the cancro adaptation-common repository, then when trying to install libhybris-libhardware I get:
```
Problem: libhybris-libhardware-0.0.5.20-10.11.1.jolla.armv7hl requires libhybris-common.so.1, but this requirement cannot be provided
  uninstallable providers: libhybris-0.0.5.20-10.11.1.jolla.armv7hl[adaptation-community]
 Solution 1: Following actions will be done:
  deinstallation of mesa-llvmpipe-9.2.5+git3-1.4.3.armv7hl
  deinstallation of mesa-llvmpipe-libEGL-9.2.5+git3-1.4.3.armv7hl
  deinstallation of mesa-llvmpipe-libEGL-devel-9.2.5+git3-1.4.3.armv7hl
  deinstallation of mesa-llvmpipe-libGLESv2-9.2.5+git3-1.4.3.armv7hl
  deinstallation of mesa-llvmpipe-libGLESv2-devel-9.2.5+git3-1.4.3.armv7hl
  deinstallation of mesa-llvmpipe-libglapi-9.2.5+git3-1.4.3.armv7hl
  deinstallation of mesa-llvmpipe-libwayland-egl-9.2.5+git3-1.4.3.armv7hl
  deinstallation of patterns-sailfish-qt5-devel-basic-0.10.2-10.5.1.jolla.noarch
  deinstallation of patterns-sailfish-qt5-devel-full-0.10.2-10.5.1.jolla.noarch
  deinstallation of patterns-sailfish-configuration-sdk-target-0.10.2-10.5.1.jolla.noarch
 Solution 2: do not install libhybris-libhardware-0.0.5.20-10.11.1.jolla.armv7hl
 Solution 3: break libhybris-libhardware-0.0.5.20-10.11.1.jolla.armv7hl by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/3/c] (c):
```
I can pick 'Solution 3' but then when it required libhybris proper, I can only pick between `[1/2/c]` (i.e. nuke some packages or don't install).
Is this what you did?

The build is now in a different state:
```
/srv/mer/toolings/SailfishOS-2.1.3.7/opt/cross/bin/armv7hl-meego-linux-gnueabi-ld: warning: libhybris-common.so.1, needed by /srv/mer/targets/SailfishOS-2.1.3.7-armv7hl/usr/lib/libhardware.so, not found (try using -rpath or -rpath-link)
/srv/mer/toolings/SailfishOS-2.1.3.7/opt/cross/bin/armv7hl-meego-linux-gnueabi-ld: warning: libandroid-properties.so.1, needed by /srv/mer/targets/SailfishOS-2.1.3.7-armv7hl/usr/lib/libhardware.so, not found (try using -rpath or -rpath-link)
/srv/mer/targets/SailfishOS-2.1.3.7-armv7hl/usr/lib/libhardware.so: undefined reference to `android_dlsym'
/srv/mer/targets/SailfishOS-2.1.3.7-armv7hl/usr/lib/libhardware.so: undefined reference to `android_dlopen'
collect2: error: ld returned 1 exit status```

**Comment by piggz** [comment]
I would go with option 1.  Hybris for a device should provide the GL acceleration headers, and llvmpipe wont be needed. (no idea how this will affect the rest of the build engine though for Qt creator!)

**Comment by b100dian** [comment]
It worked! with some caveats, of course: I did force the build engine that way but it didn't deploy on the emulator (ldd didn't find the same libhardware etc).
However I added the real device as deployement target and it rocked! even breakpoints work.
Thanks for this project and for the help!

**Comment by piggz** [comment]
Out of interest, what are you working on

**Comment by b100dian** [comment]
Nothing in particular, just ramping up in sailfish development and using the Mi4 as a daily driver. Your app is useful on this device, saidinesh pointed it out in the xda-forums cancro sailfish thread. I will also be tackling slackfish, saliorgram, and plan to make a deezer client when I get comfortable. You can write at my username at gmail if you want.
Thanks again! I think I can close this bug now:).
